# Generated by Django 4.2.4 on 2023-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
